name: fwfh_webview
version: 0.6.2+2
description: WidgetFactory extension to render IFRAME with the official WebView plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=3.0.0"
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.8.5+3
  webview_flutter: ^3.0.4

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core
  fwfh_text_style:
    path: ../fwfh_text_style

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  measurer: ^2.1.1
